x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  cassandra-1:
    image: cassandra:4.1
    logging: *default-logging
    container_name: cassandra-node1
    environment:
      - CASSANDRA_SEEDS=cassandra-node1, cassandra-node2
      - CASSANDRA_CLUSTER_NAME=EncurtaURLCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=512M
    volumes:
      - cassandra_data_1:/var/lib/cassandra
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  cassandra-2:
    image: cassandra:4.1
    logging: *default-logging
    container_name: cassandra-node2
    environment:
      - CASSANDRA_SEEDS=cassandra-node1, cassandra-node2
      - CASSANDRA_CLUSTER_NAME=EncurtaURLCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node2
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node2
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=512M
    volumes:
      - cassandra_data_2:/var/lib/cassandra
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    depends_on:
      cassandra-1:
        condition: service_healthy

  cassandra-3:
    image: cassandra:4.1
    logging: *default-logging
    container_name: cassandra-node3
    environment:
      - CASSANDRA_SEEDS=cassandra-node1, cassandra-node2
      - CASSANDRA_CLUSTER_NAME=EncurtaURLCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node3
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node3
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=512M
    volumes:
      - cassandra_data_3:/var/lib/cassandra
    networks:
      - cassandra-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    depends_on:
      cassandra-1:
        condition: service_healthy
      cassandra-2:
        condition: service_healthy

  cassandra-init:
    image: cassandra:4.1
    logging: *default-logging
    container_name: cassandra-init
    volumes:
      - ./init.cql:/init.cql
    command: >
      bash -c "echo 'Aguardando Cassandra...' &&
      sleep 05 &&
      cqlsh --request-timeout=90 cassandra-node1 -f /init.cql &&
      echo 'Script init.cql executado com sucesso!'"
    networks:
      - cassandra-net
    depends_on:
      cassandra-1:
        condition: service_healthy
      cassandra-2:
        condition: service_healthy
      cassandra-3:
        condition: service_healthy

  redis-snowflake:
    image: redis:7.2-alpine
    logging: *default-logging
    container_name: redis-cache-snowflake
    networks:
      - cassandra-net
    command: redis-server --maxmemory 16mb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-url:
    image: redis:7.2-alpine
    logging: *default-logging
    container_name: redis-cache-url
    networks:
      - cassandra-net
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-request:
    image: redis:7.2-alpine
    logging: *default-logging
    container_name: redis-cache-request
    networks:
      - cassandra-net
    command: redis-server --maxmemory 32mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  loki:
    image: grafana/loki:2.9.10
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    networks:
      - cassandra-net
    volumes:
      - ./observabilidade/loki-config-exemplo.yml:/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:v3.11.3
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=48h'
      - '--storage.tsdb.retention.size=512MB'
    networks:
      - cassandra-net
    volumes:
      - ./observabilidade/prometheus-config-exemplo.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.3.1-ubuntu
    ports:
      - "3000:3000"
    env_file:
      - ./observabilidade/grafana-exemplo.env
    networks:
      - cassandra-net
    depends_on:
      - loki
      - prometheus

  encurta-url:
    container_name: encurta-url
    build:
      context: ../backend/encurta-url
      dockerfile: Dockerfile
    env_file:
      - ./env/encurta-url.env
    networks:
      - cassandra-net
    depends_on:
      cassandra-init:
        condition: service_completed_successfully
      redis-snowflake:
        condition: service_healthy
      redis-url:
        condition: service_healthy

  qrcode:
    container_name: qrcode
    build:
      context: ../backend/qrcode
      dockerfile: Dockerfile
    env_file:
      - ./env/qrcode.env
    networks:
      - cassandra-net
    depends_on:
      - encurta-url

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - encurta-url
      - qrcode
    networks:
      - cassandra-net

volumes:
  cassandra_data_1:
  cassandra_data_2:
  cassandra_data_3:

networks:
  cassandra-net:
    driver: bridge
