spring.application.name=qrcode

#server
server.connection-timeout=${SERVER_CONNECTION_TIMEOUT}
server.tomcat.keep-alive=${SERVER_TOMCAT_KEEP_ALIVE}
server.port=${SERVER_PORT}

#GRPC
grpc.client.encurtaurl.address=${GRPC_ADDRESS}
grpc.client.encurtaurl.negotiation-type=${GRPC_NEGOTIATION_TYPE}
