spring.application.name=qrcode

#server
server.connection-timeout=${SERVER_CONNECTION_TIMEOUT}
server.tomcat.keep-alive=${SERVER_TOMCAT_KEEP_ALIVE}
server.port=${SERVER_PORT}

# Nucleo
nucleo.limitadorchamada.maximo-requisicao=10
nucleo.limitadorchamada.intervalo=30

# Redis
redis.request.host=${REDIS_REQUEST_HOST}
redis.request.port=${REDIS_REQUEST_PORT}
redis.request.timeout=1000
redis.request.connect-timeout=1000

#GRPC
grpc.client.encurtaurl.address=${GRPC_ADDRESS}
grpc.client.encurtaurl.negotiation-type=${GRPC_NEGOTIATION_TYPE}
